### ISSUE TITLE
Can't use percent sign (%) in string

### ISSUE THREAD

**Issue by jackbentley** [nelmio/alice#665]
I can't find a way to use a string with a `%` in it.

E.g `a%b`, `%c`, `100%`

It looks like there isn't any escape values for the optional DSL.

**Comment by theofidry** [comment]
@jackbentley which version or alice are you using?

**Comment by jackbentley** [comment]
Heres a bit more info:

#### Version
```
v3.0.0-beta.3
```

#### Example `fixture.yml`
```yaml
App\Entity\Car:
    car1:
        set:
            someVariable: a%b
```

#### Example Loader
```php
<?php

$loader = new Nelmio\Alice\Loader\NativeLoader();
$objects = $loader->loadFile('fixture.yml');
```

#### Output
```
PHP Fatal error:  Uncaught Nelmio\Alice\Throwable\Exception\FixtureBuilder\ExpressionLanguage\LexException: Could not lex the value "%b". in /var/{...}/vendor/nelmio/alice/src/Throwable/Exception/FixtureBuilder/ExpressionLanguage/ExpressionLanguageExceptionFactory.php:69
Stack trace:
#0 /var/{...}/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Lexer/SubPatternsLexer.php(119): Nelmio\Alice\Throwable\Exception\FixtureBuilder\ExpressionLanguage\ExpressionLanguageExceptionFactory::createForCouldNotLexValue('%b')
#1 /var/{...}/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Lexer/SubPatternsLexer.php(83): Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Lexer\SubPatternsLexer->lexFragment(Object(Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Lexer\ReferenceLexer), '%b')
#2 /var/{...}/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Lexer/FunctionLexer.php(57): Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Lexer\SubPatternsLexer->lex('a%b')
#3 /var/ in /var/{...}/vendor/nelmio/alice/src/Throwable/Exception/FixtureBuilder/ExpressionLanguage/ExpressionLanguageExceptionFactory.php on line 69
```

**Comment by jackbentley** [comment]
Seems to be working fine on `2.2.2`, however 😃
