### ISSUE TITLE
Breaking changes in 2.3.2; (local) variables, datetime convertion

### ISSUE THREAD

**Issue by Mvannes** [nelmio/alice#824]
Hi, 
All of  our projects using Nelmio/Alice with dependency on `^2.3.0` just broke down. There seem to be two major problems with the `2.3.2` tag that break things in a way that is not expected of a simple patch. 

# \DateTime conversion from strings is no longer working.
Given the following class:
``` php
<?php

namespace Test\Entity;

class TestDate
{
    /**
     * @var \DateTime
     */
    private $date;

    public function __construct(\DateTime $date)
    {
        $this->date = $date;
    }
}
``` 
And a `.yml` fixture declaration like so: 
``` yml
Test\Entity\TestDate:
    date:
        __construct:
            - 2017-23-10 23:10:15
```

We get no errors in `2.3.1` 

But in `2.3.2` we get the following error:
```
.PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Test\Entity\TestDate::__construct() must be an instance of DateTime, boolean given, called in /home/mvannes/projects/test-entities/vendor/nelmio/alice/src/Generator/Instantiator/Chainable/NoCallerMethodCallInstantiator.php on line 41 and defined in /home/mvannes/projects/test-entities/src/Entity/TestDate.php:12
Stack trace:
#0 /home/mvannes/projects/test-entities/vendor/nelmio/alice/src/Generator/Instantiator/Chainable/NoCallerMethodCallInstantiator.php(41): Test\Entity\TestDate->__construct(false)
#1 /home/mvannes/projects/test-entities/vendor/nelmio/alice/src/Generator/Instantiator/Chainable/AbstractChainableInstantiator.php(44): Nelmio\Alice\Generator\Instantiator\Chainable\NoCallerMethodCallInstantiator->createInstance(Object(Nelmio\Alice\Definition\Fixture\TemplatingFixture))
#2 /home/mvannes/projects/test-entities/vendor/nelmio/alice/src/Generator/Insta in /home/mvannes/projects/test-entities/vendor/nelmio/alice/src/Throwable/Exception/Generator/Instantiator/InstantiationExceptionFactory.php on line 26
```

# (local) is no longer a recognized flag.

Using the same class as in our previous test case, if we define the date as a local variable like so:
```
\DateTime (local):
    date:
        __construct:
            - 2017-23-10 23:10:15

Test\Entity\TestDate:
    date:
        __construct:
            - '@date'
```

We again, get no error in `2.3.1`, but when we up the version to `2.3.2` we get the following error.
```
.PHP Fatal error:  Uncaught Nelmio\Alice\Throwable\Exception\FixtureBuilder\Denormalizer\FlagParser\FlagParserNotFoundException: No suitable flag parser found to handle the element "local". in /home/mvannes/projects/test-entities/vendor/nelmio/alice/src/Throwable/Exception/FixtureBuilder/Denormalizer/FlagParser/FlagParserExceptionFactory.php:23
Stack trace:
#0 /home/mvannes/projects/test-entities/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/FlagParser/FlagParserRegistry.php(56): Nelmio\Alice\Throwable\Exception\FixtureBuilder\Denormalizer\FlagParser\FlagParserExceptionFactory::createForNoParserFoundForElement('local')
#1 /home/mvannes/projects/test-entities/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/FlagParser/ElementFlagParser.php(56): Nelmio\Alice\FixtureBuilder\Denormalizer\FlagParser\FlagParserRegistry->parse('local')
#2 /home/mvannes/projects/test-entities/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/SimpleFixtureBagDenormalizer.php(61): in /home/mvannes/projects/test-entities/vendor/nelmio/alice/src/Throwable/Exception/FixtureBuilder/Denormalizer/FlagParser/FlagParserExceptionFactory.php on line 23
```

Would love to see this fixed, because despite these being deprecated, I don't think the intention could be that this patch serves as a BC break

**Comment by theofidry** [comment]
Should be fixed, I did a mistake when releasing 2.3.2, it was based on master instead of 2.x 😕

**Comment by Mvannes** [comment]
Our Jenkins is filled with green again! Thanks! :)

**Comment by theofidry** [comment]
🎉
